name: Enable Auto Merge on Pull Request

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto Merge
        uses: actions/github-script@v7
        with:
          script: |
            // Define the query to find the Pull Request ID
            const findPRQuery = `query FindPullRequestId($OWNER_NAME: String!, $REPO_NAME: String!, $PR_NUMBER: Int!) {
              repository(owner: $OWNER_NAME, name: $REPO_NAME) {
                pullRequest(number: $PR_NUMBER) {
                  id
                }
              }
            }`;

            // Variables for the query
            const variables = {
              OWNER_NAME: context.repo.owner,
              REPO_NAME: context.repo.repo,
              PR_NUMBER: context.issue.number
            };

            // Make the query request
            const prData = await github.graphql(findPRQuery, variables);
            const pullRequestId = prData.repository.pullRequest.id;

            // Define the mutation to enable auto-merge
            const enableAutoMergeMutation = `mutation EnableAutoMerge($PULL_REQUEST_ID: ID!) {
              enablePullRequestAutoMerge(input: {
                pullRequestId: $PULL_REQUEST_ID,
                mergeMethod: SQUASH
              }) {
                pullRequest {
                  number
                  title
                  autoMergeRequest {
                    enabledAt
                    mergeMethod
                  }
                }
              }
            }`;

            // Execute the mutation
            await github.graphql(enableAutoMergeMutation, { PULL_REQUEST_ID: pullRequestId });
