name: Enable Auto-Merge for PRs

on:
  pull_request:
    types: [opened, reopened]

permissions: read-all

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          QUERY_PR_ID=$(cat <<EOF
            query {
              repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
                pullRequest(number: $PR_NUMBER) {
                  id
                }
              }
            }
          EOF
          )
          PR_ID=$(echo "$QUERY_PR_ID" | gh api graphql --input - -q '.data.repository.pullRequest.id')

          ENABLE_AUTOMERGE_MUTATION=$(cat <<EOF
            mutation {
              enablePullRequestAutoMerge(input: {pullRequestId: "$PR_ID", mergeMethod: SQUASH}) {
                clientMutationId
              }
            }
          EOF
          )
          gh api graphql --input - -f query="$ENABLE_AUTOMERGE_MUTATION"
