name: Enable Auto Merge on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened

permissions: read-all

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable Auto Merge
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/auto-merge.js');
            await script({ github, context });
