name: Lint PR Title
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          python - <<EOF
          import re
          import os

          pattern = r'^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9-]+\))?:\s[a-z0-9\s-]+[a-z0-9\s]$'
          title = os.getenv("INPUT_PULL_REQUEST_TITLE")

          if not re.match(pattern, title):
              print("::error::Pull request title must start with 'PR-' followed by a number.")
              exit(1)
          EOF
        env:
          INPUT_PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
