name: Lint Pull Request Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: read-all

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Pull Request Title
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const prTitle = context.payload.pull_request.title;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const issueNumberRegex = /Resolves #(\d+)/;
            const compliantTitleRegex = /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9-]+\))?:\s[a-z0-9\s-]+[a-z0-9\s]\n\nResolves #\d+$/;

            const isTitleCompliant = compliantTitleRegex.test(prTitle);
            const issueMatch = prTitle.match(issueNumberRegex);
            const linkedIssueNumber = issueMatch ? parseInt(issueMatch[1], 10) : null;

            let conclusion = 'success';
            let summary = 'Pull request title is compliant and linked to an issue with a matching title.';

            if (!isTitleCompliant || !linkedIssueNumber) {
              conclusion = 'failure';
              summary = 'Pull request title is non-compliant or not linked to an issue.';
            } else {
              const { data: linkedIssue } = await github.rest.issues.get({
                owner,
                repo,
                issue_number: linkedIssueNumber,
              });

              if (linkedIssue.title !== prTitle.split('\n')[0]) {
                conclusion = 'failure';
                summary = 'Pull request title does not match the linked issue title.';
              }
            }

            // Create or update a check run
            await github.rest.checks.create({
              owner,
              repo,
              name: 'Lint Pull Request Title',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: 'Lint Result',
                summary: summary,
              },
              pull_request: prNumber
            });
