name: Lint PR Title and Associated Issue Title
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title and Associated Issue Title
        run: |
          pattern="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9-]+\))?:\s[a-z0-9\s-]+[a-z0-9\s]$"
          title="${{ github.event.pull_request.title }}"
          pr_number="${{ github.event.pull_request.number }}"
          repo="${{ github.repository }}"
          api_url="${{ github.api_url }}"

          issue_title=$(gh issue view $pr_number --json title -R $repo --jq '.title')

          if [[ ! "$title" =~ $pattern ]]; then
            echo "::error::Pull request title must follow Conventional Commits."
            exit 1
          elif [[ "$title" != "$issue_title" ]]; then
            echo "::error::Pull request title '$title' does not match the associated issue title '$issue_title'."
            exit 2
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
