name: Lint Issue Title

on:
  issues:
    types: [opened, edited]

permissions: read-all

jobs:
  manage-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Open or Close Issue Based on Title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title;
            const issueState = context.payload.issue.state;
            const compliantTitleRegex = /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9-]+\))?:\s[a-z0-9\s-]+[a-z0-9\s]$/;
            const isTitleCompliant = compliantTitleRegex.test(title);

            const commentBody = `
              # :warning: Issue Title Format Error
              This issue has been closed due to a non-compliant title.

              Please update the title to comply with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

              ## Format
              \`<type>(<scope>): <subject>\`

              It is entirely lowercase.

              ## Type
              \`feat\`: A new feature
              \`fix\`: A bug fix
              \`docs\`: Documentation only changes
              \`style\`: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
              \`refactor\`: A code change that neither fixes a bug nor adds a feature
              \`perf\`: A code change that improves performance
              \`test\`: Adding missing tests or correcting existing tests
              \`build\`: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
              \`ci\`: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
              \`chore\`: Other changes that don't modify src or test files
              \`revert\`: Reverts a previous commit

              ## Scope
              Additional contextual information.

              ## Subject
              Concise description of the changes. There is no punctuation at the end.
            `;

            if (isTitleCompliant && issueState === 'closed') {
              // Reopen the issue if the title is now compliant
              await github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
              });
            } else if (!isTitleCompliant && issueState === 'open') {
              // Close the issue if the title is non-compliant
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });

              await github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              });
            }
