name: Validate code in the merge queue

on:
  pull_request_review:
    types: [submitted]

permissions: read-all

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Display info
        run: |
          pwd
          tree -a -I '.git'
          git status
      - name: Run slow CI (emulated by a long sleep)
        run: sleep 300
