name: Random Failure Workflow

on:
  pull_request:
    types:
      - labeled

permissions: read-all

jobs:
  random_failure_job:
    runs-on: ubuntu-latest

    if: ${{ github.event.label.name == 'ready-to-test' }}
    steps:
      - run: echo "test"
