name: Validate code in the merge queue

on:
  pull_request: {}
  pull_request_review:
    types:
      - submitted
      - dismissed

permissions: read-all

jobs:
  validate-merge:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display info
        run: |
          pwd
          tree -a -I '.git'
          git status
      - name: Run slow CI (emulated by a long sleep)
        run: sleep 300
