name: Pre-Merge CI

on:
  issue_comment:
    types:
      - created

permissions: read-all

jobs:
  job:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '/merge' }}
    steps:
      - name: Perform merge actions
        run: echo "Merge command was issued, performing merge actions"
