name: Pre-Merge CI

on:
  issue_comment:
    types:
      - created

permissions: read-all

jobs:
  pre-merge-ci:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Comment
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [[ "$COMMENT_BODY" == "/merge" ]]; then
            echo "true"
          else
            echo "false"
          fi
